"""
Writes extractions-current.md for W19 (2026-04-24 → 2026-05-07).
"""
import pathlib

OUT = pathlib.Path(r'C:/ClaudeProjects/status_update_agent/project/extractions-current.md')

CONTENT = """\
# Current Period Extractions — Custom-CMS
**Period:** 2026-W19 (2026-04-24 → 2026-05-07)
**Status:** Verified — awaiting generate-report

---
## Health Dashboard
- Overall: 🔴 Red | Schedule: 🔴 Red | Scope: 🟡 Yellow | Budget: 🟡 Yellow
- Client's Feeling: 🟡 Yellow
  - Rationale: Three new stakeholder teams (Finance, Abuse, Ongoing Services CRDs) all actively engaged and constructive; CRD team expressed genuine excitement; demo crash managed professionally; "When does this go live?" signals urgency; overall relationship healthy but schedule pressure is acute

---
## Progress This Period
- Held detailed 2-hour Finance Review session (Apr 24) with Bev and Barry; confirmed end-to-end PO workflow (worker request → supervisor approval → finance review → Sage 300 export) and credit card reconciliation approach
- Completed Finance follow-up session (Apr 28) with expanded group including Christine; whiteboard finance dashboard design session run after live demo crashed — PO queue, credit card queue, and aging/timer requirements documented
- Confirmed finance workflow: Wabanon holds PO/CC data as source of truth for family-related expenses; Sage handles operational-only charges; finance team reviews in Wabanon then triggers export — no duplicate data entry
- Held two Abuse Investigations sessions (Apr 28 AM): detailed review of abuse module wireframes with Kelvin covering intake triggers, form routing (Peguis vs ANCHOR), 24-business-hour timer logic, access/confidentiality tiers (standard / confidential / restricted), phase transitions, evidence reference logging, coordinator dashboard, and auto-generated investigation file numbers
- Confirmed key abuse design decisions: include-based access model (not search restriction), "Valid Incident / Abuse Did Not Occur / Inconclusive" terminology replacing "Substantiated/Unsubstantiated", physical evidence never stored in Wabanon (file number reference only), final report upload triggers sign-off task for Sherry/Kelvin
- Held two Ongoing Services sessions (Apr 29) with Chief Reconciliation Directors (Melanie, Colleen, Rupin, Christina); walked through case creation, household definition logic, case assignment hierarchy, conflict-of-interest access model, case notes architecture, checklists, and placement financial sheet triggers
- Confirmed ongoing services decisions: include-based conflict-of-interest access model, case notes attach to case record (not individual person), mandatory Child Services checklist rename, face sheet auto-triggers on placement save, in-home/out-of-home toggle needed per person on case file
- Standing biweekly Tuesday meetings confirmed booked through September in Eagle Boardroom; finance team (Bev/Barry) added to Tuesday afternoon slot

---
## Decisions Made
| Decision | Made By | Date | Notes |
|----------|---------|------|-------|
| All PO request/approval/authorization workflow captured in Wabanon; only final approved export goes to Sage 300; finance team does not re-enter data | Marcus / Bev / Ross | 2026-04-24 | End-to-end workflow confirmed |
| Family/child-related credit card expenses tracked in Wabanon attached to client files; purely operational charges stay in Sage only | Marcus / Ross / Finance team | 2026-04-24 | Addresses mixed-transaction problem on Visa statements |
| Finance task routing: "Finance Assigner" role (manual queue distribution) to start; automated routing deferred to roadmap given June 30 deadline | Marcus / Ross / Finance team | 2026-04-28 | Mirrors current manual practice; automation is post-launch |
| Global holiday calendar needed in Wabanon system settings for business-hour timer accuracy | Marcus / Ross | 2026-04-28 | Affects both finance and abuse module timer SLAs |
| Abuse investigation file number: auto-generated by Wabanon on "Accept & Open Investigation" (PCFS + fiscal-year sequential) | Kelvin / Marcus | 2026-04-28 | Removes manual step; reduces risk from staff turnover |
| Abuse terminology change: "Substantiated/Unsubstantiated" → "Valid Incident / Abuse Did Not Occur / Inconclusive" | Kelvin / Marcus | 2026-04-28 | Kelvin to confirm final terms |
| Abuse access model: include-based (only explicitly granted users can view); by default: opener + Sherry + Kelvin + assigned investigator | Kelvin / Marcus | 2026-04-28 | Separate from conflict-of-interest restrictions |
| Phase transitions and closure in abuse module restricted to supervisor role (Sherry / Kelvin / Alice only can close) | Kelvin / Marcus | 2026-04-28 | Role permissions locked |
| Sensitive physical evidence (DVDs, CSAM, autopsy photos) not stored in Wabanon or Azure; case reference field links to secure physical storage only | Marcus / Ross | 2026-04-28 | Legal/data security compliance |
| Conflict-of-interest: include-based access model; conflict of interest is a reason type under Safety Confidentiality on case creation | Marcus / CRD team | 2026-04-29 | Consistent with abuse module approach |
| Case notes attach to case record, not individual person records; persons on case access notes through the case link | Marcus / CRD team | 2026-04-29 | Data architecture decision |

---
## New Action Items
| ID | Owner | Item | Due Date |
|----|-------|------|----------|
| A-149 | Marcus / Gabrielle | Produce detailed wireframes for finance dashboard (PO queue, credit card queue, aging/timer displays) and share with Bev/Barry for review | 2026-05-21 |
| A-150 | Marcus / Gabrielle | Update finance PO workflow wireframes based on Apr 24 & Apr 28 feedback (correct step sequence: worker request → supervisor approval → finance review → PO generation → receipt attachment → Sage export) | 2026-05-21 |
| A-151 | Marcus / Gabrielle | Update abuse module wireframes: correct conclusion terminology; add "notice to provide information" step; update form routing to show 3 options; add "Other" free-text to evidence reference categories; remove committee access screen; update timer logic for business hours and holidays | 2026-05-21 |
| A-152 | Ross / IDFusion | Implement global holiday calendar in Wabanon system settings to support business-hour timer calculations for finance and abuse workflows | 2026-05-21 |
| A-153 | Kelvin (PCFS) | Send finalized abuse investigation conclusion terminology (Valid Incident / Abuse Did Not Occur / Inconclusive + any others) to Ross/Marcus for implementation | 2026-05-21 |
| A-154 | Kelvin (PCFS) | Provide blank/redacted provincial abuse investigation form fields to IDFusion for copy-assist screen field mapping | 2026-05-21 |
| A-155 | Marcus | Follow up with intake team re: adding missing Manitoba CFS Act abuse issue categories to Wabanon intake form | 2026-05-21 |
| A-156 | Marcus | Clarify with ongoing services/intake team how "parenting time" is determined for case anchoring when both parents are Peguis members | 2026-05-21 |
| A-157 | Marcus / Gabrielle | Update ongoing services wireframes: add in-home/out-of-home toggle per person on case; rename "New Admission Checklist" to "Mandatory Child Services Checklist"; add director reference to case assignment view; confirm face sheet auto-trigger on placement save; add open case/file indicator column to persons-in-case table | 2026-05-21 |
| A-158 | Bev / Barry (PCFS) | Send RBC bank export file column headers (CSV format) to IDFusion for building the Wabanon credit card import template | 2026-05-21 |
| A-159 | Marcus | Schedule follow-up ongoing services wireframe review meeting with CRD team after wireframe revisions completed | 2026-05-21 |
| A-160 | Ross (IDFusion) | Document "Finance Assigner" role in Wabanon role architecture: define queue visibility and task assignment capabilities | 2026-05-21 |

---
## Action Item Status Updates
| ID | Update |
|----|--------|
| A-055 | In Progress — access model decisions made: three-tier confidentiality (standard/confidential/restricted) confirmed for abuse module; include-based conflict-of-interest model confirmed for ongoing services |
| A-083 | In Progress — live demo crashed at Apr 28 finance meeting indicating active development; environment unstable |
| A-118 | In Progress — requirements substantially documented across Apr 24 & Apr 28 sessions; wireframe work next step (see A-149, A-150) |
| A-124 | In Progress — Kelvin reviewed forms screen by screen at Apr 28; blank/redacted form for copy-assist screen still needed (see A-154) |
| A-125 | In Progress — wireframes reviewed with Kelvin; gap identified: intake form missing Manitoba CFS Act abuse categories (see A-155) |
| A-126 | Complete — two full abuse requirements sessions held Apr 28 (Parts 1 and 2) |
| A-128 | In Progress — detailed Manitoba CFS Act vs Peguis legislation discussion at Apr 28; statutory provisions referenced in wireframes |
| A-136 | In Progress — Bev/Barry walked through all finance templates Apr 24; headers and purposes confirmed; RBC CSV headers still needed (see A-158) |
| A-139 | Complete — full credit card reconciliation workflow designed: RBC export → Wabanon ingestion → card holder matching → receipt upload tasks → finance review → Sage export |
| A-141 | In Progress — Eagle Boardroom booked through September per Ross (Apr 28); Outlook/Teams invites to Bev/Barry for Tuesday finance slot still pending |
| A-145 | In Progress — case file wireframes walked through with CRD team Apr 29; significant feedback captured; revisions required |
| A-147 | Complete — two ongoing services sessions held Apr 29 (Parts 1 and 2); follow-up meeting after revisions tracked in A-159 |

---
## New Issues & Risks
| ID | Description | Severity | Owner | Due Date |
|----|-------------|---------|-------|----------|
| I-037 | Demo environment crash at Apr 28 finance meeting — Wabanon screens could not be shown; whiteboard walkthrough used instead; indicates dev environment instability risk for upcoming UAT cycles | Medium | Ross / IDFusion | 2026-05-21 |
| I-038 | Wabanon intake form incomplete — Kelvin identified current intake form is missing mandatory Manitoba CFS Act abuse issue categories required for provincial reporting; must be updated before abuse module can be finalized | Medium | Marcus | 2026-05-21 |
| I-039 | Holiday calendar missing — Wabanon timer logic does not yet account for observed holidays (including First Nations–specific and Friday holidays); required for accurate SLA tracking in finance and abuse workflows | Medium | Ross / IDFusion | 2026-05-21 |

---
## Issue Updates
| ID | Update |
|----|--------|
| I-018 | PROGRESSED: Two finance meetings produced detailed specifications for PO workflow, credit card ingestion/reconciliation, and export/import format; GL codes and account numbers referenced throughout; Sage 300 PO module specifics still to be fully clarified |
| I-029 | ONGOING: June 30 deadline cited repeatedly as hard constraint driving design tradeoffs (task automation deferred to roadmap); risk unresolved |
| I-032 | ACTIVE: Demo crash Apr 28 confirms active development ongoing but environment unstable; Azure deployment (A-115) still not confirmed completed |
| I-034 | NOTE: Kelvin mentioned abuse clerk Alice approaching retirement; auto-generated file number design partially mitigates; risk still active |
| I-035 | SUBSTANTIALLY RESOLVED: Two full sessions Apr 28 covered all major workflow elements; key decisions made; wireframe revisions now in progress — downgrade from requirements gap to minor outstanding details |

---
## Return to Green Plans

### Overall — Red (first flagged: 2025-W48)
- Complete Azure code deployment (A-115) and validate dev environment stability to unblock UAT and eliminate demo reliability risk
- Finalize abuse module and ongoing services wireframe revisions (A-151, A-157) to close the requirements phase for these modules
- Maintain Tuesday in-person cadence and weekly status reports; prioritize A-115 as the single most critical unlock

### Schedule — Red (first flagged: 2025-W48)
- Azure deployment (A-115) remains the critical-path unlock — confirm before end of W21
- Complete Iteration 1 first UAT cycle to measure actual velocity against June 30 target
- Formally re-baseline contract timeline (A-112) — all stakeholders have implicitly accepted June 30 but no signed-off schedule exists

### Scope — Yellow (first flagged: 2025-W50)
- Wireframe revisions for finance, abuse, and ongoing services must capture all Apr feedback before developer implementation begins
- New items from Apr sessions (holiday calendar, intake form categories, finance assigner role) are confirmed in-scope for V1; hold the line on further additions
- Continue deferring non-critical items (task automation, advanced reporting) to post-launch roadmap as agreed

### Budget — Yellow (first flagged: 2025-W50)
- Sage 300 PO module integration specifics still unclear — clarify before implementation scoping to avoid cost surprises
- RBC export format and credit card reconciliation workflow finalized; confirm no Azure/infrastructure surprises as UAT environment comes online
- Assess whether intake form category additions (A-155) and holiday calendar (A-152) create out-of-scope development costs

### Client's Feeling — Yellow (first flagged: 2026-W13)
- CRD and abuse teams engaged and positive — maintain momentum by delivering revised wireframes promptly after Apr sessions
- Finance team's demo crash managed via whiteboard; follow up with updated wireframes and a screen walkthrough before next Tuesday meeting
- Communicate June 30 realistic assessment clearly once Iteration 1 velocity is measurable

---
## Next Period Plan
- Complete finance dashboard wireframes (A-149, A-150) and present to Bev/Barry
- Complete abuse module wireframe revisions (A-151) incorporating Apr 28 feedback; obtain Kelvin terminology sign-off (A-153)
- Complete ongoing services wireframe revisions (A-157) and schedule follow-up CRD review meeting (A-159)
- Confirm Azure code deployment status (A-115) — remains highest-priority development milestone
- Obtain RBC CSV export headers from Bev/Barry (A-158) and Kelvin's redacted abuse forms (A-154)
- Follow up with intake team on Manitoba CFS Act category completeness (A-155)
"""

OUT.write_text(CONTENT, encoding='utf-8')
print(f'Written {OUT.stat().st_size:,} bytes to {OUT}')
